In [2]:
import numpy as np
from scipy.stats import ks_2samp
from scipy import stats
from scipy import stats
import matplotlib.pyplot as plt
import h5py
import illustris_python as il
import sys
sys.path.append('../py_files/')
#import weights
import control_sample as control
import BRAHMA_python as il_brahma
from tqdm import tqdm

In [6]:
sm5_basepath ='/orange/lblecha/aklantbhowmick/GAS_BASED_SEED_MODEL_UNIFORM_RUNS/L12p5n512/AREPO/SM5_TNG/'
merger_file_loc='/home/pranavsatheesh/host_galaxies/data/merger_files'
pop_file_path='/home/pranavsatheesh/host_galaxies/data/population_files'

In [7]:
import population_sort_mergers_and_non_mergers as pop

In [8]:

sm5_pop = pop.pop_generator(sm5_basepath,merger_file_loc,[0,0,10,1],True)

Processing snapshot number 17
8.012172948865935 17 17 8.012172948865935
4
subhalos in this snap: 73463
minN_values: [0, 0, 10, 1]
subhalos with particle cut: 255
73463 255 252
252 4
Processing snapshot number 18
7.005417045544533 18 18 7.005417045544533
6
subhalos in this snap: 85778
minN_values: [0, 0, 10, 1]
subhalos with particle cut: 450
85778 450 441
441 6
Processing snapshot number 19
6.0107573988449 19 19 6.0107573988449
19
subhalos in this snap: 98486
minN_values: [0, 0, 10, 1]
subhalos with particle cut: 695
98486 695 680
680 19
Processing snapshot number 20
4.995933468164624 20 20 4.995933468164624
33
subhalos in this snap: 110832
minN_values: [0, 0, 10, 1]
subhalos with particle cut: 1003
110832 1003 979
979 33
Processing snapshot number 21
4.0079451114652676 21 21 4.0079451114652676
57
subhalos in this snap: 119881
minN_values: [0, 0, 10, 1]
subhalos with particle cut: 1381
119881 1381 1355
1355 57
Processing snapshot number 22
3.008131071630377 22 22 3.008131071630377
126


In [9]:
sm5_pop.unique_redshifts

array([8.01217295e+00, 7.00541705e+00, 6.01075740e+00, 4.99593347e+00,
       4.00794511e+00, 3.00813107e+00, 2.00202814e+00, 1.49551217e+00,
       9.97294226e-01, 7.00106354e-01, 5.03047523e-01, 3.99926965e-01,
       2.97717685e-01, 1.97284182e-01, 9.94018026e-02, 2.22044605e-16])

In [10]:
sm5_pop.unique_snaps

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [13]:
sm5_pop.snap_remnant[0]

32

In [15]:
sm5_pop.snap_prog2[0]

31

In [16]:
sm5_pop.brahma_redshifts

array([2.50484387e+01, 2.39609608e+01, 2.30324872e+01, 2.20291718e+01,
       2.09634266e+01, 2.00464910e+01, 1.89776156e+01, 1.79630246e+01,
       1.69999610e+01, 1.60050415e+01, 1.49891732e+01, 1.40339921e+01,
       1.30025453e+01, 1.19802133e+01, 1.09756433e+01, 9.99659047e+00,
       9.00233985e+00, 8.01217295e+00, 7.00541705e+00, 6.01075740e+00,
       4.99593347e+00, 4.00794511e+00, 3.00813107e+00, 2.00202814e+00,
       1.49551217e+00, 9.97294226e-01, 7.00106354e-01, 5.03047523e-01,
       3.99926965e-01, 2.97717685e-01, 1.97284182e-01, 9.94018026e-02,
       2.22044605e-16])

In [17]:
sm5_pop.brahma_snapshots

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [20]:
sm5_pop.brahma_redshifts[0]

25.04843874971757

In [21]:
from astropy.cosmology import Planck15
from astropy import units as u

In [22]:
def z_to_tlookback(z):
    """Convert redshift to lookback time in Gyr using Planck15 cosmology."""
    return Planck15.lookback_time(z).value  # returns time in Gyr

In [24]:
brahma_tlook = z_to_tlookback(sm5_pop.brahma_redshifts)

In [25]:
np.diff(brahma_tlook)

array([-0.00857377, -0.00809646, -0.00967724, -0.01150547, -0.01107909,
       -0.01454144, -0.01572576, -0.01700634, -0.02013539, -0.02384343,
       -0.02615352, -0.03334043, -0.03970924, -0.04744458, -0.05689119,
       -0.07235612, -0.09240054, -0.12407592, -0.16770201, -0.24532148,
       -0.36288629, -0.60464532, -1.13860855, -1.00809736, -1.58473691,
       -1.43587302, -1.27227523, -0.80246865, -0.909399  , -1.02374799,
       -1.14396449, -1.3363428 ])